name: terraform-test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Start LocalStack
        run: |
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background
          
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out 
          echo "Startup complete"   

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Run some Tests against LocalStack
        run: |
          terraform test
          echo "Test Execution complete!"          