name: terratest
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Start LocalStack
        run: |
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          docker run --rm -d -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
          
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          sleep 30
          echo "Startup complete"   

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Run some Tests against LocalStack
        run: |
          cd test/
          go test -count=1
          echo "Test Execution complete!"